name: Extract DT

on: [push]

env:
  TREE: https://static.cowtransfer.com/anonymous%2F09449dcd-def6-49de-b6a6-1c7c69506955%2Fnubdt.zip?t-s=1602227500183&t-c=5bc1eb53-35bd-4bad-af28-8e113b68638f&attname=nubdt.zip
  CHECK: merlin
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Set up python
         uses: actions/setup-python@v2
         with:
           python-version: '3.8.2'

       - name: Initializing environment
         run: |
              cd /
              sudo mkdir work
              sudo apt install aria2
              sudo chmod -R 0777 work
              cd work
              
       - name: Download tree and run codename check
         run: |
              cd /work
              sudo aria2c $TREE
              mkdir 69
              unzip *.zip -d 69
              cd 69
              grep -R $CHECK * >> final.txt
       
       - name: Cat results
         run: |
             cd /work/69
             cat final.txt
